######################################################################
##
## Filename: Encoder.udo
## Created on: Sat Mar 12 10:24:00 PM Egypt Standard Time 2022
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
