######################################################################
##
## Filename: RAM.udo
## Created on: Tue Apr 05 1:46:16 PM Egypt Standard Time 2022
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
