######################################################################
##
## Filename: demux.udo
## Created on: Tue Mar 15 2:33:33 PM Egypt Standard Time 2022
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
