######################################################################
##
## Filename: Encoder.udo
## Created on: Tue May 24 10:01:36 AM Egypt Standard Time 2022
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
