######################################################################
##
## Filename: register_12_bit.udo
## Created on: Tue Mar 29 2:52:44 PM Egypt Standard Time 2022
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
