######################################################################
##
## Filename: Comparator.udo
## Created on: Fri Mar 25 3:42:29 PM Egypt Standard Time 2022
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
